### ISSUE TITLE
License

### ISSUE THREAD

**Issue by josht000** [jcmello/MSTHT#2]
Hello, can you provide an open source license to your project?

**Comment by jcmello** [comment]
The project is open source. The algorithm is described in the [scientific paper](https://doi.org/10.1109/CLEI53233.2021.9639975).

**Comment by josht000** [comment]
@jcmello  Hey Professor! Thanks for that link. Yes, excellent publication. However, for people to use software written by someone else in github you must declare that that in a written statement. We'd need a license file or the terms spelled out in the code files. Overview of licensing concepts [here.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

For example, there are the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) and the [MIT ](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt) licenses. Either are excellent choices for truly open sourced projects for others to reference. You can put the license text into a file called "LICENSE.md" into the root of your repository to make it official. 

Thanks for understanding,

Josh

**Comment by josht000** [comment]
@jcmello I see you've already added a license file! disregard. Thanks.
